---
title: "COVID-19 Global Data"
date: '`r format(Sys.Date(), "%d %B %Y")`'
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    orientation: rows
    navbar:
      - { title: "Data Source", href: "https://github.com/CSSEGISandData/COVID-19", icon: "fa-github", align: right }
runtime: shiny
---

```{r global, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(tidyverse)
library(plotly)
library(leaflet)
library(maps)
#```{bash, include=FALSE}
#cd DATA && git pull
#```
#
#setwd("/Users/alberto/Work/COVID-19/")
#
# Load Data Set for confirmed Cases
time_series_19_covid_Confirmed <- read_csv("DATA/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
# Tidy data
time_series_19_covid_Confirmed <- time_series_19_covid_Confirmed %>% pivot_longer(cols=c(-`Province/State`, -`Country/Region`, -Lat, -Long), names_to="Date", values_to="Cases" )
# Add Features
time_series_19_covid_Confirmed <- time_series_19_covid_Confirmed %>% mutate(`Case type`= "Confirmed")
#
#
# Load Data Set for Recovered Cases
# NO LONGER UPDATED IN THE REPOSITORIES 23/03/2020
#
#time_series_19_covid_Recovered <- read_csv("DATA/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv")
# Tidy data
#time_series_19_covid_Recovered <- time_series_19_covid_Recovered %>% pivot_longer(cols=c(-`Province/State`, -`Country/Region`, -Lat, -Long), names_to="Date", values_to="Cases" )
# Add Features
#time_series_19_covid_Recovered <- time_series_19_covid_Recovered %>% mutate(`Case type` = "Recovered")
#
#
# Load Data Set for Deaths Cases
time_series_19_covid_Deaths <- read_csv("DATA/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")
# Tidy data
time_series_19_covid_Deaths<- time_series_19_covid_Deaths%>% pivot_longer(cols=c(-`Province/State`, -`Country/Region`, -Lat, -Long), names_to="Date", values_to="Cases" )
# Add Features
time_series_19_covid_Deaths <- time_series_19_covid_Deaths %>% mutate(`Case type` = "Deaths")
#
#
# Merge Confirmed, Deaths
time_series_19_covid <- bind_rows(time_series_19_covid_Confirmed ,time_series_19_covid_Deaths ) %>% mutate(Date = as.Date(Date, format = '%m/%d/%y'))
#
#
# Change US to USA
time_series_19_covid$`Country/Region`[time_series_19_covid$`Country/Region` == 'US'] <- "USA"
#
#
# Unique coords per country (capital)
library(maps)
country_coords <- world.cities %>% 
  filter(capital == 1) %>%
  select(country = country.etc, lat, lng = long)
country_coords$country[country_coords$country == 'UK'] <- "United Kingdom"
country_coords$country[country_coords$country == 'Korea South'] <- "Korea, South"
country_coords$country[country_coords$country == 'Czech Republic'] <- 'Czechia'
country_coords$country[country_coords$country == 'Serbia and Montenegro'] <- 'Serbia'
country_coords$country[country_coords$country == 'Macedonia'] <- 'North Macedonia'
country_coords$country[country_coords$country == 'Ivory Coast	'] <- 'Cote d\'Ivoire	'
#
#
# Word population dataset
pop <- read_csv("DATA_EXTERNAL/API_SP.POP.TOTL_DS2_en_csv_v2_887275/API_SP.POP.TOTL_DS2_en_csv_v2_887275.csv", skip = 3)
# Manually hack some names
pop$`Country Name`[pop$`Country Code` == 'USA'] <- "USA"
pop$`Country Name`[pop$`Country Name` == 'Bahamas, The'] <- "Bahamas"
pop$`Country Name`[pop$`Country Name` == 'Brunei Darussalam'] <- "Brunei"
pop$`Country Name`[pop$`Country Name` == 'Congo, Dem. Rep.'] <- "Congo (Brazzaville)"
pop$`Country Name`[pop$`Country Name` == 'Congo, Rep.'] <- "Congo (Kinshasa)"
pop$`Country Name`[pop$`Country Name` == 'Czech Republic'] <- "Czechia"
pop$`Country Name`[pop$`Country Name` == 'Egypt, Arab Rep.'] <- "Egypt"
pop$`Country Name`[pop$`Country Name` == 'Gambia, The'] <- "Gambia"
pop$`Country Name`[pop$`Country Name` == 'Iran, Islamic Rep.'] <- "Iran"
pop$`Country Name`[pop$`Country Name` == 'Korea, Rep.'] <- "Korea, South"
pop$`Country Name`[pop$`Country Name` == 'Kyrgyz Republic'] <- "Kyrgyzstan"
pop$`Country Name`[pop$`Country Name` == 'Russian Federation'] <- "Russia"
pop$`Country Name`[pop$`Country Name` == 'St. Lucia'] <- "Saint Lucia"
pop$`Country Name`[pop$`Country Name` == 'St. Vincent and the Grenadines'] <- "Saint Vincent and the Grenadines"
pop$`Country Name`[pop$`Country Name` == 'Slovak Republic'] <- "Slovakia"
pop$`Country Name`[pop$`Country Name` == 'Syrian Arab Republic'] <- "Syria"
pop$`Country Name`[pop$`Country Name` == 'Venezuela, RB'] <- "Venezuela"
pop$`Country Name`[pop$`Country Name` == 'Venezuela, RB'] <- "Venezuela"
#
pop <- pop %>% select(c(-`Indicator Name`, -`Indicator Code`)) %>% 
  pivot_longer(cols=c(-`Country Name`, -`Country Code`), 
               names_to='Year', values_to='Population') %>% 
  drop_na(Population) %>% 
  group_by(`Country Name`, `Country Code`) %>% 
  filter(Year == max(Year)) %>% select(cols=c(-`Country Code`, -`Year`))
# Join covid data with word population data
time_series_19_covid <- time_series_19_covid %>% left_join(., pop, by=c("Country/Region"="Country Name"))
#
#
# Time series with the daily number of cases per country
time_series_19_covid_country_daily <- time_series_19_covid %>% 
  select(c('Date', 'Country/Region', 'Population' ,'Case type', 'Cases')) %>% 
  mutate(daily_cases = `Cases` - lag(`Cases`)) %>% filter(daily_cases >= 0) %>% 
  group_by(`Date`, `Country/Region`, `Population`, `Case type`) %>% 
  summarize(sum(daily_cases)) %>% rename(`Total Cases`=`sum(daily_cases)`) %>%
  left_join(., country_coords, by = c("Country/Region"="country"))
#
#
# Time series with the total number of cases per country
time_series_19_covid_country <- time_series_19_covid %>% 
  select(c('Date', 'Country/Region', 'Population' ,'Case type', 'Cases')) %>% 
  group_by(`Date`, `Country/Region`, `Population`, `Case type`) %>% 
  summarize(sum(Cases)) %>% rename(`Total Cases`=`sum(Cases)`) %>%
  left_join(., country_coords, by = c("Country/Region"="country"))

summary_country <- time_series_19_covid_country %>%
  filter(Date == max(time_series_19_covid_country$Date)) %>% 
  pivot_wider(names_from = `Case type`, values_from = `Total Cases`)  %>%
  select(c('Country/Region', 'Population', 'Confirmed', 'Deaths')) %>% arrange(desc(`Confirmed`))

summary_totals <- time_series_19_covid %>% group_by(`Date`, `Case type`) %>% summarize(sum(Cases)) %>% rename(`Total Cases`=`sum(Cases)`) %>% ungroup()

data_summary_per_country <- time_series_19_covid_country %>% 
    pivot_wider(names_from = `Case type`, values_from = `Total Cases`) 
  
data_summary_per_country_norm <- data_summary_per_country %>% mutate(`Confirmed` = 100000 * `Confirmed` / `Population`) 
data_summary_per_country_norm <- data_summary_per_country %>% mutate(`Deaths` = 100000 * `Deaths` / `Population`)

data_summary_per_country_daily <- time_series_19_covid_country_daily %>% 
    pivot_wider(names_from = `Case type`, values_from = `Total Cases`)
  
data_summary_per_country_daily_norm <- data_summary_per_country_daily %>% mutate(`Confirmed` = 100000 * `Confirmed` / `Population`) 
data_summary_per_country_daily_norm <- data_summary_per_country_daily %>% mutate(`Deaths` = 100000 * `Deaths` / `Population`)

```

Sidebar {.sidebar}
=====================================

```{r}
sliderInput("daterange", "Date:",
            min(time_series_19_covid$Date), 
            max(time_series_19_covid$Date),
            value = max(time_series_19_covid$Date),
            step=1,
            animate=TRUE)

#dateRangeInput("daterange", "Date range:",
#                start = max(time_series_19_covid$Date)-20,
#                end   = max(time_series_19_covid$Date))

radioButtons("casecount", "Case counts:",
               c("Total" = "Total",
                 "Daily" = "Daily"))

radioButtons("scale", "Axis Scale:", 
                   c("Linear" = "lin",
                     "Logarithmic" = "log"))

checkboxInput("norm", "Per 100'000 inhabitants", FALSE)

selectInput("casetype", "Select Case type:",
      unique(time_series_19_covid$`Case type`),
      selected='Confirmed',
      multiple=FALSE
    )

selectInput("country", "Select Countries:",
       unique(summary_country$`Country/Region`),
      selected=c('Italy', 'France', 'Switzerland'),
      multiple=TRUE
    )

```

Map
=====================================  

Row
-------------------------------------

```{r}
# Summary totals
summary_totals_selected_date <- reactive({
  summary_totals %>% filter(Date == input$daterange)
})
```
  
### Confirmed
```{r}
renderValueBox({
  valueBox(summary_totals_selected_date() %>% filter(`Case type` == "Confirmed") %>% select(`Total Cases`), 
           icon = "fa-stethoscope", color="#f39c12")
})
```

### Deaths
```{r}
renderValueBox({
  valueBox(summary_totals_selected_date() %>% filter(`Case type` == "Deaths") %>% select(`Total Cases`), 
           icon = "fa-sad-tear", color='red')
})  
```

Row
-------------------------------------

###
```{r}

m <- reactive({
  
  # Grab relevant dataframe
  if(input$casecount == 'Total'){
    if(input$norm){
       data <- data_summary_per_country_norm
    } else {
      data <- data_summary_per_country
    }
  } else if(input$casecount == 'Daily'){
    if(input$norm){
       data <- data_summary_per_country_daily_norm
    } else {
      data <- data_summary_per_country_daily
    }
  }
  # Filter
  data <- data %>% filter(Date == input$daterange)
  # Popup text
  mytext <- paste("Country: ", data$`Country/Region`, "<br/>", "Population: ", format(data$`Population`, format="d", big.mark="'"), "<br/>", "Confirmed: ", sprintf("%.2f", data$`Confirmed`), "<br/>", "Deaths: ", sprintf("%.2f", data$`Deaths`), sep="") %>%
  lapply(htmltools::HTML)
    
  if(input$casetype == 'Confirmed'){
    c <- "#f39c12"
  } else {
    c <- "red"
  }
  
  data %>% 
    rename(counts = input$casetype) %>% 
    leaflet() %>% addTiles() %>%
  addProviderTiles("OpenStreetMap.Mapnik") %>%
  addCircleMarkers(lat=~`lat`, lng =~`lng`, 
                   radius=~5*log10(counts), 
                   layerId = ~unique(`Country/Region`), 
                   color = c, fillOpacity = 0.5,
                   stroke=FALSE, label = mytext)

  })
  
## leaflet map
renderLeaflet({m()})
```

Evolution
=====================================  

Row
-----------------------------------------------------------------------

###

```{r}

g_daily <- reactive({
  
  # Grab the relevant dataset
  if ( input$casecount == 'Daily' ){
    gg <- time_series_19_covid_country_daily 
  } else if(input$casecount == 'Total') {
    gg <- time_series_19_covid_country
  }
  # Filter
  gg <- gg %>% filter(`Country/Region` %in% input$country) %>% filter(Date >= min(time_series_19_covid$Date) & Date <= input$daterange ) %>% filter(`Case type` == input$casetype)
  # Normalize total counts if required
  if(input$norm){
    gg <- gg %>% mutate(`Total Cases` = 100000 * `Total Cases` / `Population`)
  }
  # Define the plot
  gg <- gg %>% ggplot(aes(x=Date, y=`Total Cases`,color=`Country/Region`)) + 
    geom_line(size=1) + geom_point(size=2, stroke=1) + 
    theme(legend.title = element_blank())
  # Adjust axis label
  if ( input$casecount == 'Daily' ){
    gg <- gg + ylab(paste('Daily Cases: ', input$casetype))
  } else if (input$casecount == 'Total') {
    gg <- gg + ylab(paste('Total Cases: ', input$casetype))
  }
  # Adgust log scale
  if(input$scale == 'log'){
    gg <- gg + scale_y_log10() 
  }
  # Done
  gg
})

renderPlotly({g_daily()})

```

Summary
=====================================  

Row
-------------------------------------

###

```{r}
t <- reactive({
  # Grab relevant dataframe
  if(input$casecount == 'Total'){
    if(input$norm){
       data <- data_summary_per_country_norm
    } else {
      data <- data_summary_per_country
    }
  } else if(input$casecount == 'Daily'){
    if(input$norm){
       data <- data_summary_per_country_daily_norm
    } else {
      data <- data_summary_per_country_daily
    }
  }
  
  # Filter
  data <- data %>% filter(Date == input$daterange) %>% select(c(`Country/Region`, `Population`, `Confirmed`, `Deaths`)) %>% arrange(desc(`Confirmed`)) %>% ungroup()
  
  data <- data %>% mutate( `Population` = format(`Population`, format="d", big.mark="'"))
  
  if(input$norm){
      data <- data %>% mutate( `Confirmed` = format(round(data$Confirmed,2), format="d", big.mark="'", nsmall=2))
      data <- data %>% mutate( `Deaths` = format(round(data$Deaths,2), format="d", big.mark="'", nsmall=2))
    } else {
      data <- data %>% mutate( `Confirmed` = format(round(data$Confirmed,2), format="d", big.mark="'", nsmall=0))
      data <- data %>% mutate( `Deaths` = format(round(data$Deaths,2), format="d", big.mark="'", nsmall=0))
    }
  
})

DT::renderDataTable( DT::datatable(t(), 
                                   selection = 'single', 
                                   options = list(paging = FALSE, scrollY="75vh", 
                                                  columnDefs = list(
                                                    list(
                                                      className = 'dt-right', targets = 3:5
                                                      )
                                                    )
                                                  )
                                   )
                     )

```

```{r}
# Reactive based on the row selected in the previous table
#g <- reactive({
#
#    if ( is_null(input$tab_rows_selected) ){
#      tmp <- time_series_19_covid_country %>% group_by(`Date`, `Case type`) %>% summarise(`Total #Cases` = sum(`Total Cases`))
#    } else {
#      filter_country <- tab[input$tab_rows_selected, ]$`Country/Region`
#      tmp <- time_series_19_covid_country %>% filter(`Country/Region` == filter_country)
#    }
#  
#    tmp %>% ggplot(aes(x=Date, y=`Total Cases`, color=`Case type`)) + geom_line() + #geom_point(size=2) + ylab("") + scale_color_manual(values=c("#f39c12", "red", "#52be80")) + #theme(legend.title = element_blank(), legend.position = "none") + facet_grid(rows = vars(`Case #type`), scales='free_y')
#    
#})
#
#renderPlotly({g()})
#
#
```